# APPLICATION
spring.application.name=api
server.port=${PORT:8080}

# DEFAULT PROFILE
spring.profiles.active=dev

# LANGUAGE / LOCALE
spring.web.locale=pt_BR
spring.web.locale-resolver=fixed

# TIMEZONE
spring.jackson.time-zone=America/Sao_Paulo
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

# HIKARI
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# JPA / HIBERNATE
spring.jpa.open-in-view=false

# FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

# JACKSON
spring.jackson.deserialization.fail-on-unknown-properties=true

# MULTIPART
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=10MB

# ACTUATOR
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# JWT BASE
jwt.access-token-expiration=60000
jwt.refresh-token-expiration=120000
jwt.issuer=garcias-api

# COOKIES
cookie.secure=false
cookie.same-site=Lax