# DATABASE - POSTGRESQL PRODUCAO (RENDER)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# REDIS PRODUCAO (RENDER)
spring.data.redis.url=${REDIS_URL:}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

# JPA / HIBERNATE PROD
spring.jpa.show-sql=false

# LOGGING PROD
logging.level.root=WARN
logging.level.garcias.api=INFO

# JWT PROD
jwt.secret=${JWT_SECRET}
