# DATABASE - POSTGRESQL LOCAL
spring.datasource.url=jdbc:postgresql://localhost:5432/eloa_mercados_panificacoes
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# REDIS LOCAL
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

# JPA / HIBERNATE DEV
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# LOGGING DEV
logging.level.root=INFO
logging.level.garcias.api=DEBUG

# JWT DEV
jwt.secret=v7GFd2Z5qCs/kyCdCKX21Eo5Ver3Ii9DdOWhqk7hNCtNfhjKB9LtNBl+CWZiwPK+CobVHOeN1olBOhFNCXa4Kg==

# Setup Initial (DEV)
app.setup.access-key=A1B-C2D-E3F-!
app.setup.cpf=12345678909
