spring.datasource.url=jdbc:postgresql://localhost:5432/eloa_mercados_panificacoes
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.root=INFO
logging.level.garcias.api=DEBUG

jwt.secret=v7GFd2Z5qCs/kyCdCKX21Eo5Ver3Ii9DdOWhqk7hNCtNfhjKB9LtNBl+CWZiwPK+CobVHOeN1olBOhFNCXa4Kg==
jwt.refresh-token-expiration=604800

app.setup.access-key=AAA-111-BBB-!
app.setup.cpf=12345678909

app.cors.allowed-origins=http://localhost:4200

