spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT:5432}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.url=${REDIS_URL:}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

spring.jpa.show-sql=false

app.setup.access-key=${SETUP_ACCESS_KEY}
app.setup.cpf=${SETUP_CPF}

logging.level.root=WARN
logging.level.garcias.api=INFO

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION:900000}
jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION:604800}

cookie.secure=true
cookie.same-site=None

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://eloa-mercados-e-panificacoes.vercel.app}

